import { createReactFormSDK } from "@mercura-aps/frontend-form-sdk/react";

export const {
    SDKStore,
    useSDK,
    useConfigs,
    useForms,
    useLocalization,
    useReset,
    useFormByCurrentConfigId,
    useValuesByCurrentConfigId,
    useValuesByConfigId,
    useForm,
    useFormByConfigId,
    useValues,
    useAuth,
    useFinishedConfigs,
    useNumberFormatter,
    useContactDetails,
    useAddons,
    useAppearance,
    useFormCategories,
    useOptions,
    useSubmit,
} = createReactFormSDK();
